[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "affine"
port = 3010
host = "${main_domain}"

[config.env]
SERVICE_USER_POSTGRES = "${username}"
SERVICE_PASSWORD_POSTGRES = "${password:32}"
SERVICE_URL_AFFINE = "https://${main_domain}"
