services:
  emulatorjs:
    image: linuxserver/emulatorjs:1.9.2
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - SUBFOLDER=/
      - TZ=$TZ
    expose:
      - "3000"
      - "4001"
      - "80"
    volumes:
      - emulatorjs-config:/config
      - emulatorjs-data:/data
      - /ROMS/nes:/data/nes/roms
    restart: unless-stopped
volumes:
  emulatorjs-config: {}
  emulatorjs-data: {}
