services:
  whoogle:
    image: benbusby/whoogle-search:latest
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://127.0.0.1:5000
      interval: 2s
      timeout: 10s
      retries: 15
