[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "jdownloader2"
port = 5800
host = "${main_domain}"

[config.env]
PUID = ""
PGID = ""
TZ = ""
MYJDOWNLOADER_EMAIL = ""
MYJDOWNLOADER_PASSWORD = "${password:32}"
MYJDOWNLOADER_DEVICE_NAME = ""
JDOWNLOADER_HEADLESS = ""
