[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "mongo"
port = 27017
host = "${main_domain}"

[config.env]
MONGO_INITDB_ROOT_USERNAME = ""
MONGO_INITDB_ROOT_PASSWORD = "${password:32}"
