services:
  phpldapadmin:
    image: osixia/openldap:${OPENLDAP_VERSION}
    environment:
      LDAP_ORGANISATION: ${OPENLDAP_LDAP_ORGANISATION}
      LDAP_DOMAIN: ${ROOT_DOMAIN}
      LDAP_ADMIN_PASSWORD: ${OPENLDAP_LDAP_ADMIN_PASSWORD}
    volumes:
      - phpldapadmin-db:/var/lib/ldap
      - phpldapadmin-config:/etc/ldap/slapd.d
    restart: always
  phpldapadmin-admin:
    image: osixia/phpldapadmin:${PHPLDAPADMIN_VERSION}
    environment:
      PHPLDAPADMIN_TRUST_PROXY_SSL: "true"
      PHPLDAPADMIN_LDAP_HOSTS: phpldapadmin
      PHPLDAPADMIN_SERVER_ADMIN: ${PHPLDAPADMIN_ADMIN_EMAIL}
      PHPLDAPADMIN_SERVER_PATH: https://phpldapadmin-admin.${ROOT_DOMAIN}
      PHPLDAPADMIN_HTTPS: "false"
    depends_on:
      - phpldapadmin
    restart: always
volumes:
  phpldapadmin-db: {}
  phpldapadmin-config: {}
