services:
  homeassistant-1:
    image: ghcr.io/home-assistant/home-assistant:2026.7.3
    environment:
      TZ: ${TZ}
    volumes:
      - homeassistant-1-localtime:/etc/localtime
      - homeassistant-1-config:/config
    expose:
      - "8123"
    restart: always
volumes:
  homeassistant-1-localtime: {}
  homeassistant-1-config: {}
