services:
  pingvin-share:
    image: stonith404/pingvin-share
    environment:
      TRUST_PROXY: false
    expose:
      - "3000"
    volumes:
      - pingvin-share-data:/opt/app/backend/data
      - pingvin-share-img:/opt/app/frontend/public/img
    restart: unless-stopped
volumes:
  pingvin-share-data: {}
  pingvin-share-img: {}
