services:
  semaphore:
    image: semaphoreui/semaphore:v2.18.28
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${SEMAPHORE_DB_PASSWORD}
      SEMAPHORE_DB_HOST: semaphore-db
      SEMAPHORE_DB_PORT: "5432"
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore
      SEMAPHORE_ADMIN_PASSWORD: ${SEMAPHORE_ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ADMIN_EMAIL: ${SEMAPHORE_ADMIN_EMAIL}
      SEMAPHORE_ADMIN: ${SEMAPHORE_ADMIN_NAME}
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${SEMAPHORE_ACCESS_KEY_ENCRYPTION}
      SEMAPHORE_LDAP_ACTIVATED: no
      TZ: ${TZ}
    volumes:
      - semaphore-repositories:/repositories
    expose:
      - "3000"
    restart: always
  semaphore-db:
    image: postgres:14
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: ${SEMAPHORE_DB_PASSWORD}
      POSTGRES_DB: semaphore
    volumes:
      - semaphore-data:/var/lib/postgresql/data
    restart: always
volumes:
  semaphore-repositories: {}
  semaphore-data: {}
