services:
  mongo-express:
    image: mongo-express:${MONGOEXPRESS_VERSION}
    environment:
      ME_CONFIG_MONGODB_SERVER: ${ME_SERVER_ADDRESS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_SERVER_ADMIN_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_SERVER_ADMIN_PASSWORD}
      ME_CONFIG_MONGODB_PORT: ${ME_SERVER_PORT}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_DASHBOARD_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_DASHBOARD_PASSWORD}
      ME_CONFIG_SITE_COOKIESECRET: mongo-express${GENSEC16}
      ME_CONFIG_SITE_SESSIONSECRET: mongo-express${GENSEC16}
    expose:
      - "8081"
    restart: always
