[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "api"
port = 8080
host = "${main_domain}"

[config.env]
SERVICE_URL_EVO = "https://${main_domain}"
SERVICE_USER_POSTGRES = "${username}"
SERVICE_PASSWORD_POSTGRES = "${password:32}"
SERVICE_PASSWORD_AUTHENTICATIONAPIKEY = "${password:32}"
