[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "plausible-ce"
port = 8193
host = "${main_domain}"

[config.env]
APP_PROTOCOL = "https"
APP_DOMAIN = "${main_domain}"
PLAUSIBLE_SECRET_KEY_BASE = "${hash:32}"
PLAUSIBLE_DB_PASSWORD = "${hash:32}"
PLAUSIBLE_DISABLE_REGISTRATION = ""
PLAUSIBLE_ENABLE_EMAIL_VERIFICATION = ""
PLAUSIBLE_TOTP_VAULT_KEY = "${hash:32}"
PLAUSIBLE_GOOGLE_CLIENT_ID = ""
PLAUSIBLE_GOOGLE_CLIENT_SECRET = ""
PLAUSIBLE_MAXMIND_LICENSE_KEY = ""
PLAUSIBLE_MAXMIND_EDITION = ""
PLAUSIBLE_MAILER_ADAPTER = ""
PLAUSIBLE_MAILER_EMAIL = ""
PLAUSIBLE_MAILER_NAME = ""
PLAUSIBLE_SMTP_HOST_ADDR = ""
PLAUSIBLE_SMTP_HOST_PORT = ""
PLAUSIBLE_SMTP_USER_NAME = ""
PLAUSIBLE_SMTP_USER_PWD = "${password:32}"
PLAUSIBLE_SMTP_HOST_SSL_ENABLED = ""
PLAUSIBLE_SMTP_RETRIES = ""
PLAUSIBLE_POSTMARK_API_KEY = ""
PLAUSIBLE_MAILGUN_API_KEY = ""
PLAUSIBLE_MAILGUN_DOMAIN = ""
PLAUSIBLE_MAILGUN_BASE_URI = ""
PLAUSIBLE_MANDRILL_API_KEY = ""
PLAUSIBLE_SENDGRID_API_KEY = ""
