services:
  denokv:
    image: ghcr.io/denoland/denokv:latest
    environment:
      - ACCESS_TOKEN=${SERVICE_PASSWORD_DENOKV}
    volumes:
      - ${COOLIFY_VOLUME_APP}:/data
    command: --sqlite-path /data/denokv.sqlite serve --access-token ${SERVICE_PASSWORD_DENOKV}
    healthcheck:
      test:
        - CMD
        - nc
        - -zv
        - 127.0.0.1
        - "4512"
      interval: 5s
      timeout: 5s
      retries: 3
