services:
  call-only:
    image: calcom/cal.com:${VERSION}
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_WEBAPP_URL: http://call-only.${ROOT_DOMAIN}
      NEXTAUTH_SECRET: ${SECRET_KEY_BASE}
      CALENDSO_ENCRYPTION_KEY: ${CALENDSO_ENCRYPTION_KEY}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      DATABASE_HOST: ${POSTGRES_HOST}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      DATABASE_DIRECT_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}/${POSTGRES_DB}
      GOOGLE_API_CREDENTIALS: "{}"
      EMAIL_FROM: ${EMAIL_FROM}
      EMAIL_SERVER_HOST: ${EMAIL_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PASSWORD}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
    expose:
      - "3000"
    restart: always
