services:
  boxy-hq-only:
    image: boxyhq/jackson:${BOXYHQ_JACKSON_VERSION}
    environment:
      EXTERNAL_URL: ${EXTERNAL_URL}
      SAML_AUDIENCE: ${SAML_AUDIENCE}
      JACKSON_API_KEYS: ${JACKSON_API_KEYS}
      ADMIN_PORTAL_SSO_TENANT: ${ADMIN_PORTAL_SSO_TENANT}
      ADMIN_PORTAL_SSO_PRODUCT: ${ADMIN_PORTAL_SSO_PRODUCT}
      IDP_ENABLED: ${IDP_ENABLED}
      PRE_LOADED_CONNECTION: ${PRE_LOADED_CONNECTION}
      CLIENT_SECRET_VERIFIER: ${CLIENT_SECRET_VERIFIER}
      DB_ENGINE: ${DB_ENGINE}
      DB_URL: ${DB_URL}
      DB_TYPE: ${DB_TYPE}
      DB_TTL: ${DB_TTL}
      DB_CLEANUP_LIMIT: ${DB_CLEANUP_LIMIT}
      DB_PAGE_LIMIT: ${DB_PAGE_LIMIT}
      DB_ENCRYPTION_KEY: ${DB_ENCRYPTION_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_FROM: ${SMTP_FROM}
      NEXTAUTH_ACL: ${NEXTAUTH_ACL}
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      NEXTAUTH_ADMIN_CREDENTIALS: ${NEXTAUTH_ADMIN_CREDENTIALS}
      RETRACED_HOST_URL: ${RETRACED_HOST_URL}
      RETRACED_EXTERNAL_URL: ${RETRACED_EXTERNAL_URL}
      RETRACED_ADMIN_ROOT_TOKEN: ${RETRACED_ADMIN_ROOT_TOKEN}
      TERMINUS_PROXY_HOST_URL: ${TERMINUS_PROXY_HOST_URL}
      TERMINUS_ADMIN_ROOT_TOKEN: ${TERMINUS_ADMIN_ROOT_TOKEN}
      OTEL_EXPORTER_OTLP_METRICS_ENDPOINT: ${OTEL_EXPORTER_OTLP_METRICS_ENDPOINT}
      OTEL_EXPORTER_OTLP_METRICS_HEADERS: ${OTEL_EXPORTER_OTLP_METRICS_HEADERS}
      OPENID_JWS_ALG: ${OPENID_JWS_ALG}
      OPENID_RSA_PRIVATE_KEY: ${OPENID_RSA_PRIVATE_KEY}
      OPENID_RSA_PUBLIC_KEY: ${OPENID_RSA_PUBLIC_KEY}
      PUBLIC_KEY: ${PUBLIC_KEY}
      PRIVATE_KEY: ${PRIVATE_KEY}
      BOXYHQ_LICENSE_KEY: ${BOXYHQ_LICENSE_KEY}
      WEBHOOK_URL: ${WEBHOOK_URL}
      WEBHOOK_SECRET: ${WEBHOOK_SECRET}
      node_options: ${NODE_OPTIONS}
      NEXT_TELEMETRY_DISABLED: ${NEXT_TELEMETRY_DISABLED}
    expose:
      - "5225"
    restart: always
