[variables]
main_domain = "${domain}"
external-url = "${main_domain}"
saml-audience = "$$cap_appname.$$cap_root_domain"
jackson-api-keys = "${password:64}"
admin-portal-sso-tenant = "_jackson_boxyhq"
admin-portal-sso-product = "_jackson_admin_portal"
idp-enabled = "true"
pre-loaded-connection = ""
client-secret-verifier = "${password:64}"
db-engine = "sql"
db-url = "${main_domain}"
db-type = "postgres"
db-ttl = "300"
db-cleanup-limit = "1000"
db-page-limit = "50"
db-encryption-key = ""
smtp-host = "${main_domain}"
smtp-port = "587"
smtp-user = "info@example.com"
smtp-password = ""
smtp-from = "noreply@example.com"
nextauth-acl = "tonystark@gmail.com,*@marvel.com"
nextauth-url = "${main_domain}"
nextauth-secret = "${password:64}"
nextauth-admin-credentials = ""
retraced-host-url = "${main_domain}"
retraced-external-url = "${main_domain}"
retraced-admin-root-token = ""
terminus-proxy-host-url = "${main_domain}"
terminus-admin-root-token = ""
otel-exporter-otlp-metrics-endpoint = ""
otel-exporter-otlp-metrics-headers = ""
openid-jws-alg = "RS256"
openid-rsa-private-key = ""
openid-rsa-public-key = ""
public-key = ""
private-key = ""
boxyhq-license-key = ""
webhook-url = "${main_domain}"
webhook-secret = ""
node-options = "--max-http-header-size=81920 --dns-result-order=ipv4first"
next-telemetry-disabled = "1"
boxyhq-jackson-version = "1.13.0"

[config]

[[config.domains]]
serviceName = "boxy-hq-only"
port = 5225
host = "${main_domain}"

[config.env]
EXTERNAL_URL = "${external-url}"
SAML_AUDIENCE = "${saml-audience}"
JACKSON_API_KEYS = "${jackson-api-keys}"
ADMIN_PORTAL_SSO_TENANT = "${admin-portal-sso-tenant}"
ADMIN_PORTAL_SSO_PRODUCT = "${admin-portal-sso-product}"
IDP_ENABLED = "${idp-enabled}"
PRE_LOADED_CONNECTION = "${pre-loaded-connection}"
CLIENT_SECRET_VERIFIER = "${client-secret-verifier}"
DB_ENGINE = "${db-engine}"
DB_URL = "${db-url}"
DB_TYPE = "${db-type}"
DB_TTL = "${db-ttl}"
DB_CLEANUP_LIMIT = "${db-cleanup-limit}"
DB_PAGE_LIMIT = "${db-page-limit}"
DB_ENCRYPTION_KEY = "${db-encryption-key}"
SMTP_HOST = "${smtp-host}"
SMTP_PORT = "${smtp-port}"
SMTP_USER = "${smtp-user}"
SMTP_PASSWORD = "${smtp-password}"
SMTP_FROM = "${smtp-from}"
NEXTAUTH_ACL = "${nextauth-acl}"
NEXTAUTH_URL = "${nextauth-url}"
NEXTAUTH_SECRET = "${nextauth-secret}"
NEXTAUTH_ADMIN_CREDENTIALS = "${nextauth-admin-credentials}"
RETRACED_HOST_URL = "${retraced-host-url}"
RETRACED_EXTERNAL_URL = "${retraced-external-url}"
RETRACED_ADMIN_ROOT_TOKEN = "${retraced-admin-root-token}"
TERMINUS_PROXY_HOST_URL = "${terminus-proxy-host-url}"
TERMINUS_ADMIN_ROOT_TOKEN = "${terminus-admin-root-token}"
OTEL_EXPORTER_OTLP_METRICS_ENDPOINT = "${otel-exporter-otlp-metrics-endpoint}"
OTEL_EXPORTER_OTLP_METRICS_HEADERS = "${otel-exporter-otlp-metrics-headers}"
OPENID_JWS_ALG = "${openid-jws-alg}"
OPENID_RSA_PRIVATE_KEY = "${openid-rsa-private-key}"
OPENID_RSA_PUBLIC_KEY = "${openid-rsa-public-key}"
PUBLIC_KEY = "${public-key}"
PRIVATE_KEY = "${private-key}"
BOXYHQ_LICENSE_KEY = "${boxyhq-license-key}"
WEBHOOK_URL = "${webhook-url}"
WEBHOOK_SECRET = "${webhook-secret}"
NODE_OPTIONS = "${node-options}"
NEXT_TELEMETRY_DISABLED = "${next-telemetry-disabled}"
BOXYHQ_JACKSON_VERSION = "${boxyhq-jackson-version}"
