[variables]
main_domain = "${domain}"
postgresql-version = "12.12.0"
postgresql-name = "airflow_db"
postgresql-user = "airflow_db_user"
postgresql-password = "${password:16}"
redis-version = "7.0.4"
redis-password = "${password:16}"
airflow-version = "2.3.3"
airflow-worker-version = "2.3.3"
airflow-scheduler-version = "2.3.3"
airflow-user = "airflow_user"
airflow-password = "${password:16}"
airflow-email = ""
airflow-examples = "no"
airflow-secret-key = "${password:16}"
airflow-dag-path = "airflow-dags"
airflow-py-requirements = "airflow-requstxt"
smtp-host = "${main_domain}"
smtp-port = ""
smtp-starttls = "no"
smtp-ssl = "no"
smtp-user = ""
smtp-password = ""
smtp-mail-from = ""

[config]

[[config.domains]]
serviceName = "airflow"
port = 8080
host = "${main_domain}"

[config.env]
POSTGRESQL_VERSION = "${postgresql-version}"
POSTGRESQL_NAME = "${postgresql-name}"
POSTGRESQL_USER = "${postgresql-user}"
POSTGRESQL_PASSWORD = "${postgresql-password}"
REDIS_VERSION = "${redis-version}"
REDIS_PASSWORD = "${redis-password}"
AIRFLOW_VERSION = "${airflow-version}"
AIRFLOW_WORKER_VERSION = "${airflow-worker-version}"
AIRFLOW_SCHEDULER_VERSION = "${airflow-scheduler-version}"
AIRFLOW_USER = "${airflow-user}"
AIRFLOW_PASSWORD = "${airflow-password}"
AIRFLOW_EMAIL = "${airflow-email}"
AIRFLOW_EXAMPLES = "${airflow-examples}"
AIRFLOW_SECRET_KEY = "${airflow-secret-key}"
AIRFLOW_DAG_PATH = "${airflow-dag-path}"
AIRFLOW_PY_REQUIREMENTS = "${airflow-py-requirements}"
SMTP_HOST = "${smtp-host}"
SMTP_PORT = "${smtp-port}"
SMTP_STARTTLS = "${smtp-starttls}"
SMTP_SSL = "${smtp-ssl}"
SMTP_USER = "${smtp-user}"
SMTP_PASSWORD = "${smtp-password}"
SMTP_MAIL_FROM = "${smtp-mail-from}"
ROOT_DOMAIN = "${main_domain}"
