[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "odoo"
port = 8069
host = "${main_domain}"

[config.env]
SERVICE_USER_POSTGRES = "${username}"
SERVICE_PASSWORD_POSTGRES = "${password:32}"
