[variables]
main_domain = "${domain}"
novu-image-version = "0.8.0"
novu-image-url = "${main_domain}"
redis-version = "7.0.5"
mongo-version = "6.0.2"
environment = "prod"
novu-docker-hosted-environment = "true"
puid = "1000"
pgid = "1000"
novu-jwt-secret = "${password:32}"
novu-store-encryption-key = "${password:32}"
novu-disable-user-registration = "false"
novu-api-port = "3000"
novu-api-sentry-dsn = ""
redis-port = "6379"
redis-db-index = "2"
mongo-db = "novu"
novu-port-embed = "4701"
novu-port-widget = "4500"
novu-port-application = "4200"
novu-port-websocket = "3002"
novu-s3-local-stack = "http://localhost:4566"
novu-s3-bucket-name = "novu-local"
novu-s3-region = "us-east-1"
novu-aws-access-key-id = "test"
novu-aws-secret-access-key = "test"

[config]

[[config.domains]]
serviceName = "novu"
port = 80
host = "${main_domain}"

[config.env]
NOVU_IMAGE_VERSION = "${novu-image-version}"
NOVU_IMAGE_URL = "${novu-image-url}"
REDIS_VERSION = "${redis-version}"
MONGO_VERSION = "${mongo-version}"
ENVIRONMENT = "${environment}"
NOVU_DOCKER_HOSTED_ENVIRONMENT = "${novu-docker-hosted-environment}"
PUID = "${puid}"
PGID = "${pgid}"
NOVU_JWT_SECRET = "${novu-jwt-secret}"
NOVU_STORE_ENCRYPTION_KEY = "${novu-store-encryption-key}"
NOVU_DISABLE_USER_REGISTRATION = "${novu-disable-user-registration}"
NOVU_API_PORT = "${novu-api-port}"
NOVU_API_SENTRY_DSN = "${novu-api-sentry-dsn}"
REDIS_PORT = "${redis-port}"
REDIS_DB_INDEX = "${redis-db-index}"
MONGO_DB = "${mongo-db}"
NOVU_PORT_EMBED = "${novu-port-embed}"
NOVU_PORT_WIDGET = "${novu-port-widget}"
NOVU_PORT_APPLICATION = "${novu-port-application}"
NOVU_PORT_WEBSOCKET = "${novu-port-websocket}"
NOVU_S3_LOCAL_STACK = "${novu-s3-local-stack}"
NOVU_S3_BUCKET_NAME = "${novu-s3-bucket-name}"
NOVU_S3_REGION = "${novu-s3-region}"
NOVU_AWS_ACCESS_KEY_ID = "${novu-aws-access-key-id}"
NOVU_AWS_SECRET_ACCESS_KEY = "${novu-aws-secret-access-key}"
ROOT_DOMAIN = "${main_domain}"
