[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "redmine"
port = 3000
host = "${main_domain}"

[config.env]
SERVICE_PASSWORD_64_REDMINE = "${base64:64}"
SERVICE_USER_POSTGRES = "${username}"
SERVICE_PASSWORD_64_POSTGRES = "${base64:64}"
