[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "supertokens"
port = 3567
host = "${main_domain}"

[config.env]
SERVICE_USER_MYSQL = "${username}"
SERVICE_PASSWORD_MYSQL = "${password:32}"
