services:
  siyuan:
    image: b3log/siyuan:v3.3.5
    volumes:
      - siyuan_workspace:/siyuan/workspace
    environment:
      - TZ=${TZ:-UTC}
      - PUID=1000
      - PGID=1000
      - SIYUAN_ACCESS_AUTH_CODE=${SERVICE_PASSWORD_SIYUAN}
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - --quiet
        - http://127.0.0.1:6806/api/system/version
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 20s
