services:
  tinyauth:
    image: ghcr.io/steveiliop56/tinyauth:v5.0.7
    environment:
      TINYAUTH_UI_TITLE: ${TINYAUTH_APP_TITLE}
      TINYAUTH_APPURL: ${TINYAUTH_APP_URL}
      TINYAUTH_AUTH_USERS: ${TINYAUTH_USERS}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTID: ${TINYAUTH_GITHUB_CLIENT_ID}
      TINYAUTH_OAUTH_PROVIDERS_GITHUB_CLIENTSECRET: ${TINYAUTH_GITHUB_CLIENT_SECRET}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTID: ${TINYAUTH_GOOGLE_CLIENT_ID}
      TINYAUTH_OAUTH_PROVIDERS_GOOGLE_CLIENTSECRET: ${TINYAUTH_GOOGLE_CLIENT_SECRET}
      TINYAUTH_OAUTH_WHITELIST: ${TINYAUTH_OAUTH_WHITELIST}
    volumes:
      - tinyauth-data:/data
    expose:
      - "3000"
    restart: always
volumes:
  tinyauth-data: {}
