[variables]
main_domain = "${domain}"
secret-key-base = "${password:32}"
bigbluebutton-endpoint = "https://scalelite.eunarede.stream/bigbluebutton/"
bigbluebutton-secret = ""
safe-hosts = "$$cap_appname.$$cap_root_domain"
allow-greenlight-accounts = "true"
default-registration = "open"
web-concurrency = "2"
enable-ssl = "false"
room-features = "mute-on-join,require-moderator-approval,anyone-can-start,all-join-moderator,recording"
pagination-number = "10"
number-of-rows = "10"
enable-google-calendar-button = "true"
google-analytics-tracking-id = ""
recaptcha-site-key = ""
recaptcha-secret-key = ""
db-adapter = "postgresql"
cable-adapter = "postgresql"
db-host = "${main_domain}"
db-port = "5432"
db-name = ""
db-username = "postgres"
db-password = ""
allow-mail-notifications = "false"
smtp-test-recipient = ""
smtp-server = ""
smtp-port = ""
smtp-domain = "${main_domain}"
smtp-username = ""
smtp-password = ""
smtp-auth = ""
smtp-starttls-auto = ""
smtp-sender = ""
maintenance-mode = ""
maintenance-window = ""
help-url = "${main_domain}"
aws-access-key-id = ""
aws-secret-access-key = ""
aws-region = ""
aws-bucket = ""

[config]

[[config.domains]]
serviceName = "greenlight-greenlight"
port = 80
host = "${main_domain}"

[config.env]
SECRET_KEY_BASE = "${secret-key-base}"
BIGBLUEBUTTON_ENDPOINT = "${bigbluebutton-endpoint}"
BIGBLUEBUTTON_SECRET = "${bigbluebutton-secret}"
SAFE_HOSTS = "${safe-hosts}"
ALLOW_GREENLIGHT_ACCOUNTS = "${allow-greenlight-accounts}"
DEFAULT_REGISTRATION = "${default-registration}"
WEB_CONCURRENCY = "${web-concurrency}"
ENABLE_SSL = "${enable-ssl}"
ROOM_FEATURES = "${room-features}"
PAGINATION_NUMBER = "${pagination-number}"
NUMBER_OF_ROWS = "${number-of-rows}"
ENABLE_GOOGLE_CALENDAR_BUTTON = "${enable-google-calendar-button}"
GOOGLE_ANALYTICS_TRACKING_ID = "${google-analytics-tracking-id}"
RECAPTCHA_SITE_KEY = "${recaptcha-site-key}"
RECAPTCHA_SECRET_KEY = "${recaptcha-secret-key}"
DB_ADAPTER = "${db-adapter}"
CABLE_ADAPTER = "${cable-adapter}"
DB_HOST = "${db-host}"
DB_PORT = "${db-port}"
DB_NAME = "${db-name}"
DB_USERNAME = "${db-username}"
DB_PASSWORD = "${db-password}"
ALLOW_MAIL_NOTIFICATIONS = "${allow-mail-notifications}"
SMTP_TEST_RECIPIENT = "${smtp-test-recipient}"
SMTP_SERVER = "${smtp-server}"
SMTP_PORT = "${smtp-port}"
SMTP_DOMAIN = "${smtp-domain}"
SMTP_USERNAME = "${smtp-username}"
SMTP_PASSWORD = "${smtp-password}"
SMTP_AUTH = "${smtp-auth}"
SMTP_STARTTLS_AUTO = "${smtp-starttls-auto}"
SMTP_SENDER = "${smtp-sender}"
MAINTENANCE_MODE = "${maintenance-mode}"
MAINTENANCE_WINDOW = "${maintenance-window}"
HELP_URL = "${help-url}"
AWS_ACCESS_KEY_ID = "${aws-access-key-id}"
AWS_SECRET_ACCESS_KEY = "${aws-secret-access-key}"
AWS_REGION = "${aws-region}"
AWS_BUCKET = "${aws-bucket}"
