services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    environment:
      - _APP_URL=$SERVICE_URL_PROWLARR
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-America/Toronto}
    volumes:
      - prowlarr-config:/config
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:9696/ping
      interval: 2s
      timeout: 10s
      retries: 15
