services:
  pgadmin4:
    image: dpage/pgadmin4:${PGADMIN4_VERSION}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PASSWORD}
    volumes:
      - pgadmin4-data:/var/lib/pgadmin
    restart: always
volumes:
  pgadmin4-data: {}
