[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "freshrss"
port = 80
host = "${main_domain}"

[config.env]
SERVICE_USER_POSTGRESQL = "${username}"
SERVICE_PASSWORD_POSTGRESQL = "${password:32}"
