services:
  plex:
    image: lscr.io/linuxserver/plex:1.41.3
    environment:
      PGID: $PGID
      PUID: $PUID
      VERSION: docker
      CPU_FALLBACK: "true"
      NVIDIA_VISIBLE_DEVICES: all
    devices:
      - /dev/dri:/dev/dri
      - /dev/dvb:/dev/dvb
    volumes:
      - plex-nvidia-config:/config
      - plex-nvidia-media:/Media
    restart: unless-stopped
volumes:
  plex-nvidia-config: {}
  plex-nvidia-media: {}
