services:
  tandoor:
    image: ghcr.io/tandoorrecipes/recipes:2.6.13
    environment:
      SECRET_KEY: ${TANDOOR_SECRET_KEY}
      DB_ENGINE: django.db.backends.postgresql
      GUNICORN_MEDIA: "1"
      POSTGRES_HOST: tandoor-db
      POSTGRES_PORT: "5432"
      POSTGRES_USER: tandoor
      POSTGRES_PASSWORD: ${TANDOOR_POSTGRESS_PASSWORD}
      POSTGRES_DB: tandoordb
    depends_on:
      tandoor-db:
        condition: service_healthy
    volumes:
      - tandoor-staticfiles:/opt/recipes/staticfiles
      - tandoor-mediafiles:/opt/recipes/mediafiles
    expose:
      - "80"
    restart: always
  tandoor-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PORT: "5432"
      POSTGRES_USER: tandoor
      POSTGRES_PASSWORD: ${TANDOOR_POSTGRESS_PASSWORD}
      POSTGRES_DB: tandoordb
    volumes:
      - tandoor-data:/var/lib/postgresql/data
    restart: always
volumes:
  tandoor-staticfiles: {}
  tandoor-mediafiles: {}
  tandoor-data: {}
