services:
  proxyscotch:
    image: hoppscotch/proxyscotch:v0.1.4
    environment:
      - PROXYSCOTCH_TOKEN=${SERVICE_PASSWORD_TOKEN}
      - PROXYSCOTCH_ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
      - PROXYSCOTCH_BANNED_OUTPUTS=${BANNED_OUTPUTS}
      - PROXYSCOTCH_BANNED_DESTS=${BANNED_DESTS}
