[variables]
main_domain = "${domain}"
version = "2.1.1"
tz = "Europe/Paris"
puid = "1000"
pgid = "1000"
appname-downloads = "/downloads"
appname-watch = "/watch"

[config]

[[config.domains]]
serviceName = "deluge"
port = 8112
host = "${main_domain}"

[config.env]
VERSION = "${version}"
TZ = "${tz}"
PUID = "${puid}"
PGID = "${pgid}"
APPNAME_DOWNLOADS = "${appname-downloads}"
APPNAME_WATCH = "${appname-watch}"
