services:
  vitodeploy:
    image: vitodeploy/vito:${VITO_VERSION}
    environment:
      APP_KEY: ${VITO_APP_KEY}
      APP_URL: https://vitodeploy.${ROOT_DOMAIN}
      NAME: ${VITO_ADMIN_NAME}
      EMAIL: ${VITO_ADMIN_EMAIL}
      PASSWORD: ${VITO_ADMIN_PASSWORD}
    volumes:
      - vitodeploy-storage:/var/www/html/storage
      - vitodeploy-plugins:/var/www/html/app/Vito/Plugins
    expose:
      - "80"
    restart: always
volumes:
  vitodeploy-storage: {}
  vitodeploy-plugins: {}
