[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "esphome"
port = 6052
host = "${main_domain}"

[config.env]
SERVICE_USER_ADMIN = "${username}"
SERVICE_PASSWORD_ADMIN = "${password:32}"
