[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "frontend"
port = 8080
host = "${main_domain}"

[config.env]
SERVICE_REALBASE64_64_PENPOT = "${base64:64}"
SERVICE_URL_FRONTEND_8080 = "https://${main_domain}"
SERVICE_USER_POSTGRES = "${username}"
SERVICE_PASSWORD_POSTGRES = "${password:32}"
SERVICE_USER_MINIO = "${username}"
SERVICE_PASSWORD_MINIO = "${password:32}"
