[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "classicpress"
port = 80
host = "${main_domain}"

[config.env]
SERVICE_USER_CLASSICPRESS = "${username}"
SERVICE_PASSWORD_CLASSICPRESS = "${password:32}"
SERVICE_PASSWORD_ROOT = "${password:32}"
