services:
  photoview-mariadb:
    image: mariadb:${MARIADB_VERSION}
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "1"
      MYSQL_DATABASE: ${MARIADB_DB}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASS}
    volumes:
      - photoview-mariadb-data:/var/lib/mysql
    restart: always
  photoview:
    image: viktorstrate/photoview:${PHOTOVIEW_VERSION}
    environment:
      PHOTOVIEW_DATABASE_DRIVER: mysql
      PHOTOVIEW_MYSQL_URL: ${MARIADB_USER}:${MARIADB_PASS}@tcp(photoview-mariadb)/${MARIADB_DB}
      PHOTOVIEW_LISTEN_IP: 0.0.0.0
      PHOTOVIEW_LISTEN_PORT: "80"
      PHOTOVIEW_MEDIA_CACHE: /app/cache
      MAPBOX_TOKEN: ${MAPBOX_TOKEN}
    volumes:
      - photoview-media-cache:/app/cache
      - ${PHOTOS_PATH}:/photos
    depends_on:
      - photoview-mariadb
    restart: always
volumes:
  photoview-mariadb-data: {}
  photoview-media-cache: {}
