[variables]
main_domain = "${domain}"
keila-version = "0.12.2"
keila-port = "4000"
keila-db-enable-ssl = "false"
keila-user = ""
keila-password = "${password:16}"
keila-url-path = "/"
keila-url-schema = "http"
keila-url-port = "80"
keila-secret-key-base = "${password:64}"
keila-disable-registration = "true"
keila-disable-precedence-header = "false"
keila-mailer-type = "smtp"
keila-mailer-smtp-host = "${main_domain}"
keila-mailer-smtp-port = "587"
keila-mailer-smtp-user = ""
keila-mailer-smtp-password = ""
keila-captcha-provider = "hcaptcha"
keila-captcha-site-key = ""
keila-captcha-secret-key = ""
keila-captcha-url = "${main_domain}"
postgres-version = "14.5"
postgres-user = "keila"
postgres-password = "${password:16}"
postgres-database = "keila"

[config]

[[config.domains]]
serviceName = "keila"
port = 80
host = "${main_domain}"

[config.env]
KEILA_VERSION = "${keila-version}"
KEILA_PORT = "${keila-port}"
KEILA_DB_ENABLE_SSL = "${keila-db-enable-ssl}"
KEILA_USER = "${keila-user}"
KEILA_PASSWORD = "${keila-password}"
KEILA_URL_PATH = "${keila-url-path}"
KEILA_URL_SCHEMA = "${keila-url-schema}"
KEILA_URL_PORT = "${keila-url-port}"
KEILA_SECRET_KEY_BASE = "${keila-secret-key-base}"
KEILA_DISABLE_REGISTRATION = "${keila-disable-registration}"
KEILA_DISABLE_PRECEDENCE_HEADER = "${keila-disable-precedence-header}"
KEILA_MAILER_TYPE = "${keila-mailer-type}"
KEILA_MAILER_SMTP_HOST = "${keila-mailer-smtp-host}"
KEILA_MAILER_SMTP_PORT = "${keila-mailer-smtp-port}"
KEILA_MAILER_SMTP_USER = "${keila-mailer-smtp-user}"
KEILA_MAILER_SMTP_PASSWORD = "${keila-mailer-smtp-password}"
KEILA_CAPTCHA_PROVIDER = "${keila-captcha-provider}"
KEILA_CAPTCHA_SITE_KEY = "${keila-captcha-site-key}"
KEILA_CAPTCHA_SECRET_KEY = "${keila-captcha-secret-key}"
KEILA_CAPTCHA_URL = "${keila-captcha-url}"
POSTGRES_VERSION = "${postgres-version}"
POSTGRES_USER = "${postgres-user}"
POSTGRES_PASSWORD = "${postgres-password}"
POSTGRES_DATABASE = "${postgres-database}"
ROOT_DOMAIN = "${main_domain}"
