[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "transmission-vpn"
port = 9091
host = "${main_domain}"

[config.env]
TRANSMISSION_PUID = ""
TRANSMISSION_PGID = ""
TZ = ""
TRANSMISSION_USERNAME = "${username}"
TRANSMISSION_PASSWORD = "${password:32}"
TRANSMISSION_OVPN_PROVIDER = ""
TRANSMISSION_OVPN_CONFIG = ""
TRANSMISSION_OVPN_USERNAME = ""
TRANSMISSION_OVPN_PASSWORD = "${password:32}"
TRANSMISSION_OVPN_LOCAL_NETWORK = ""
TRANSMISSION_WEBUI = ""
TRANSMISSION_CREATE_TUN_DEVICE = ""
TRANSMISSION_PEER_DNS = ""
TRANSMISSION_DHT_ENABLED = ""
TRANSMISSION_LPD_ENABLED = ""
TRANSMISSION_PEX_ENABLED = ""
TRANSMISSION_BLOCKLIST_ENABLED = ""
TRANSMISSION_BLOCKLIST_URL = "https://${main_domain}"
