services:
  imagor-s3:
    image: shumc/imagor:${IMAGOR_VERSION}
    environment:
      PORT: "80"
      IMAGOR_UNSAFE: ${ENV_IMAGOR_UNSAFE}
      IMAGOR_SECRET: ${ENV_IMAGOR_SECRET}
      AWS_ACCESS_KEY_ID: ${ENV_AWS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${ENV_AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${ENV_AWS_REGION}
      S3_ENDPOINT: ${ENV_S3_ENDPOINT}
      S3_LOADER_BUCKET: ${ENV_S3_LOADER_BUCKET}
      S3_LOADER_BASE_DIR: ${ENV_S3_LOADER_BUCKET_DIR}
      S3_STORAGE_BUCKET: ${ENV_S3_STORAGE_BUCKET}
      S3_STORAGE_BASE_DIR: ${ENV_S3_STORAGE_BUCKET_DIR}
      S3_RESULT_STORAGE_BUCKET: ${ENV_S3_RESULT_STORAGE_BUCKET}
      S3_RESULT_STORAGE_BASE_DIR: ${ENV_S3_RESULT_STORAGE_BUCKET_DIR}
    restart: always
