[variables]
main_domain = "${domain}"
version = "2.6.4"
port-sync = "55555"

[config]

[[config.domains]]
serviceName = "resilio-sync"
port = 8888
host = "${main_domain}"

[config.env]
VERSION = "${version}"
PORT_SYNC = "${port-sync}"
