services:
  wordpress-only-wordpress:
    image: wordpress:${WP_VERSION}
    environment:
      WORDPRESS_DB_HOST: ${DB_HOST}:3306
      WORDPRESS_DB_NAME: ${DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${DB_PREFIX}
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASS}
    volumes:
      - wordpress-only-wp-data:/var/www/html
    restart: always
volumes:
  wordpress-only-wp-data: {}
