services:
  bitcoind:
    image: lncm/bitcoind:v28.0
    command:
      - -dbcache=${BITCOIND_DB_CACHE:-450}
      - -maxmempool=${BITCOIND_MAX_MEMPOOL:-300}
      - -listen=${BITCOIND_LISTEN:-1}
      - -server=${BITCOIND_SERVER:-1}
      - -rpcallowip=0.0.0.0/0
      - -rpcbind=0.0.0.0
      - -prune=${BITCOIND_PRUNING:-0}
      - -maxconnections=${BITCOIND_MAXPEERS:-125}
      - -txindex=${BITCOIND_TXINDEX:-1}
      - -peerbloomfilters=${BITCOIND_BLOOM_FILTERS:-1}
      - -blockfilterindex=${BITCOIND_BLOCK_FILTER:-1}
      - -peerblockfilters=${BITCOIND_BLOCK_FILTER:-1}
    user: 0:0
    volumes:
      - bitcoind-bitcoin:/root/.bitcoin
    expose:
      - "8333"
    restart: always
volumes:
  bitcoind-bitcoin: {}
