[variables]
main_domain = "${domain}"

[config]

[[config.domains]]
serviceName = "observium"
port = 80
host = "${main_domain}"

[config.env]
SERVICE_URL_OBSERVIUM = "https://${main_domain}"
SERVICE_PASSWORD_OBSERVIUMADMIN = "${password:32}"
SERVICE_USER_OBSERVIUMADMIN = "${username}"
SERVICE_PASSWORD_MARIADB = "${password:32}"
SERVICE_USER_MARIADB = "${username}"
SERVICE_PASSWORD_MARIADBROOT = "${password:32}"
